#! /usr/bin/perl -w

use warnings;
use strict;


if(`uname -a` =~ m/Darwin/) {
	if(`which py2applet` ne "") {
		print "Creating Gitso.app ";
		`rm -f setup.py`;
		`rm -rf dist`;
		
		print "..";
		`py2applet --make-setup Gitso.py`;
		
		print "..";
		`python setup.py py2app`;
		
		print "..";
		`cp arch/osx/Info.plist dist/Gitso.app/Contents/`;
		`cp copyright dist/Gitso.app/Contents/Resources/`;
		`cp PythonApplet.icns dist/Gitso.app/Contents/Resources/`;
		
		`tar xvfz arch/osx/OSXvnc.tar.gz`;
		`mv OSXvnc dist/Gitso.app/Contents/Resources/`;

		`tar xvfz arch/osx/vncviewer.tar.gz`;
		`mv vncviewer dist/Gitso.app/Contents/Resources/`;
		print " [done]\n";
		
		print "Creating Gitso.dmg ";
		`rm -f Gitso.dmg`;
		
		`mkdir dist/Gitso`;
		`cp arch/osx/dmg_DS_Store dist/Gitso/.DS_Store`;
		`ln -s /Applications/ dist/Gitso/Applications`;
		
		`mv "dist/Gitso.app" "dist/Gitso/"`;
		`cp -r arch/osx/Readme.rtfd dist/Gitso/Readme.rtfd`;
		
		print "...";
		`hdiutil create -srcfolder dist/Gitso/ Gitso.dmg`;
		print "... [done]\n";
	} else {
		print "Error, you need py2applet to be installed.";
	}
	
} elsif (`uname -a` =~ m/Linux/) {
	print "Implement makegitso for Linux\n"
}
