#!/usr/bin/env python

import sys, os, wx
sys.path.append(os.path.join(sys.path[0], '..', 'share', 'gitso'))

from Gitso import Connect

if __name__ == "__main__":
	app = wx.PySimpleApp()
	Connect(None, -1, "Gitso")
	app.MainLoop()
